// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO_u8f4h3t6k0rvSyVRHiIeknkbN6ajgs',
    appId: '1:485055222449:web:8b58f8b7ca8de01e628890',
    messagingSenderId: '485055222449',
    projectId: 'cpsc5250-hw5-6f036',
    authDomain: 'cpsc5250-hw5-6f036.firebaseapp.com',
    storageBucket: 'cpsc5250-hw5-6f036.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXiYYCKAfzhJH25jGdAnmD65BDlyoqRWs',
    appId: '1:485055222449:android:c7636aafc73db9f6628890',
    messagingSenderId: '485055222449',
    projectId: 'cpsc5250-hw5-6f036',
    storageBucket: 'cpsc5250-hw5-6f036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-y38R4L9l3MYJBMpDoCWfKxegd-ikmxM',
    appId: '1:485055222449:ios:e4541f556449682a628890',
    messagingSenderId: '485055222449',
    projectId: 'cpsc5250-hw5-6f036',
    storageBucket: 'cpsc5250-hw5-6f036.appspot.com',
    iosBundleId: 'com.example.homeworkFive',
  );
}
